services:
  mines:
    image: quay.io/str_netappontour/mines:latest
    build:
      context: .
    container_name: mines
    restart: unless-stopped
    volumes:
      - './css:/mines/css'
      - './to_encrypt:/to_encrypt'
    ports:
      - 8080:8080
 
